// Auto-generated by svg-lint. Do not edit manually.
import { ComponentType } from 'react';
import { SvgProps } from 'react-native-svg';

import FigmaSVGLandingPageIllustration from './FigmaSVGLandingPageIllustration';

export const components: { name: string; Component: ComponentType<SvgProps> }[] = [
  { name: 'FigmaSVGLandingPageIllustration', Component: FigmaSVGLandingPageIllustration },
];
