import { execSync, spawn } from 'node:child_process';
import { resolve, basename } from 'node:path';
import { existsSync, writeFileSync, readFileSync, readdirSync } from 'node:fs';
import type { Response } from 'express';

const RN_PREVIEW_DIR = resolve(import.meta.dirname, '..', 'RNPreview');
const PREVIEWS_DIR = resolve(RN_PREVIEW_DIR, 'previews');

interface ConvertOptions {
  platform?: 'ios' | 'android';
}

function toComponentName(filePath: string): string {
  return basename(filePath)
    .replace(/\.svg$/i, '')
    .replace(/[^a-zA-Z0-9]/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

async function convertSvgToComponent(svgContent: string, componentName: string): Promise<string> {
  const { transform } = await import('@svgr/core');
  const rawJsx = await transform(svgContent, {
    typescript: true,
    native: true,
    dimensions: false,
    expandProps: 'end',
    exportType: 'default',
    plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx', '@svgr/plugin-prettier'],
  }, { componentName });

  const widthMatch = svgContent.match(/width=["']?(\d+)/);
  const heightMatch = svgContent.match(/height=["']?(\d+)/);
  const vbMatch = svgContent.match(/viewBox=["'](\d+)\s+(\d+)\s+(\d+)\s+(\d+)["']/);
  const w = widthMatch ? widthMatch[1] : vbMatch ? vbMatch[3] : '24';
  const h = heightMatch ? heightMatch[1] : vbMatch ? vbMatch[4] : '24';

  const svgBodyMatch = rawJsx.match(/<Svg[^>]*>([\s\S]*?)<\/Svg>/);
  const svgBody = (svgBodyMatch ? svgBodyMatch[1] : '')
    .replace(/\s*{["']?\s*["']?}\s*/g, '\n')
    .replace(/\n{3,}/g, '\n\n');

  const importTags = new Set<string>();
  const tagRegex = /<([A-Z][a-zA-Z]*)/g;
  let m;
  while ((m = tagRegex.exec(rawJsx)) !== null) {
    if (m[1] !== 'Svg' && m[1] !== 'View') importTags.add(m[1]);
  }
  const svgImports = importTags.size > 0
    ? `Svg, { ${[...importTags].join(', ')}, SvgProps }`
    : 'Svg, { SvgProps }';

  return `import * as React from 'react';
import { View } from 'react-native';
import ${svgImports} from 'react-native-svg';

const originalWidth = ${w};
const originalHeight = ${h};
const aspectRatio = originalWidth / originalHeight;

const ${componentName}: React.FC<SvgProps> = (props: SvgProps) => {
  return (
    <View style={{ width: '100%', aspectRatio }}>
      <Svg width="100%" height="100%" viewBox={\`0 0 \${originalWidth} \${originalHeight}\`} {...props}>
${svgBody}
      </Svg>
    </View>
  );
};

export default ${componentName};
`;
}

function regenerateRegistry(): void {
  const files = readdirSync(PREVIEWS_DIR).filter(f => f.endsWith('.tsx') && f !== 'index.ts');
  const imports: string[] = [];
  const entries: string[] = [];

  for (const file of files) {
    const name = file.replace(/\.tsx$/, '');
    imports.push(`import ${name} from './${name}';`);
    entries.push(`  { name: '${name}', Component: ${name} },`);
  }

  const content = `// Auto-generated by svg-lint. Do not edit manually.
import { ComponentType } from 'react';
import { SvgProps } from 'react-native-svg';

${imports.join('\n')}

export const components: { name: string; Component: ComponentType<SvgProps> }[] = [
${entries.join('\n')}
];
`;

  writeFileSync(resolve(PREVIEWS_DIR, 'index.ts'), content, 'utf-8');
}

function isMetroRunning(): boolean {
  try {
    const out = execSync('lsof -ti :8081', { encoding: 'utf-8' }).trim();
    return out.length > 0;
  } catch {
    return false;
  }
}

function launchOnSimulator(): void {
  console.log('Building and launching RNPreview on iOS Simulator...');
  execSync('npx expo run:ios', {
    cwd: RN_PREVIEW_DIR,
    stdio: 'inherit',
  });
}

export function launchOnSimulatorStreaming(res: Response): void {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
  });

  function send(data: string) {
    res.write(`data: ${JSON.stringify(data)}\n\n`);
  }

  send('Converting components...');

  const child = spawn('npx', ['expo', 'run:ios'], {
    cwd: RN_PREVIEW_DIR,
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  let done = false;

  function handleOutput(chunk: Buffer) {
    if (done) return;
    const lines = chunk.toString().split('\n').filter(Boolean);
    for (const line of lines) {
      send(line);
      if (line.includes('iOS Bundled') || line.includes('Opening on')) {
        done = true;
        res.write(`data: ${JSON.stringify('__DONE__')}\n\n`);
        res.end();
        return;
      }
      if (line.includes('error code 65') || line.includes('Build Failed')) {
        done = true;
        res.write(`data: ${JSON.stringify('__ERROR__')}\n\n`);
        res.end();
        return;
      }
    }
  }

  child.stdout.on('data', handleOutput);
  child.stderr.on('data', handleOutput);

  child.on('close', (code) => {
    if (done) return;
    done = true;
    res.write(`data: ${JSON.stringify(code === 0 ? '__DONE__' : '__ERROR__')}\n\n`);
    res.end();
  });

  res.on('close', () => {
    if (!done) child.kill();
  });
}

export async function rnPreview(svgFiles: string[], options: ConvertOptions = {}): Promise<void> {
  console.log('Converting SVGs to React Native components...');

  for (const filePath of svgFiles) {
    const absPath = resolve(filePath);
    if (!existsSync(absPath)) {
      console.error(`  File not found: ${absPath}`);
      continue;
    }

    const content = readFileSync(absPath, 'utf-8');
    const componentName = toComponentName(filePath);

    try {
      const tsx = await convertSvgToComponent(content, componentName);
      const outPath = resolve(PREVIEWS_DIR, `${componentName}.tsx`);
      writeFileSync(outPath, tsx, 'utf-8');
      console.log(`  ✓ ${basename(filePath)} → ${componentName}.tsx`);
    } catch (e: any) {
      console.error(`  ✗ ${basename(filePath)}: ${e.message}`);
    }
  }

  regenerateRegistry();
  console.log('Registry updated.');

  launchOnSimulator();
}

export async function rnPreviewPrepare(
  files: { name: string; buffer: Buffer }[]
): Promise<void> {
  for (const file of files) {
    const content = file.buffer.toString('utf-8');
    const componentName = toComponentName(file.name);
    try {
      const tsx = await convertSvgToComponent(content, componentName);
      const outPath = resolve(PREVIEWS_DIR, `${componentName}.tsx`);
      writeFileSync(outPath, tsx, 'utf-8');
    } catch (e: any) {
      console.error(`  ✗ ${file.name}: ${e.message}`);
    }
  }
  regenerateRegistry();
}

export async function rnPreviewFromBuffers(
  files: { name: string; buffer: Buffer }[],
  options: ConvertOptions = {}
): Promise<void> {
  console.log('Converting SVGs to React Native components...');

  for (const file of files) {
    const content = file.buffer.toString('utf-8');
    const componentName = toComponentName(file.name);

    try {
      const tsx = await convertSvgToComponent(content, componentName);
      const outPath = resolve(PREVIEWS_DIR, `${componentName}.tsx`);
      writeFileSync(outPath, tsx, 'utf-8');
      console.log(`  ✓ ${file.name} → ${componentName}.tsx`);
    } catch (e: any) {
      console.error(`  ✗ ${file.name}: ${e.message}`);
    }
  }

  regenerateRegistry();
  console.log('Registry updated.');

  launchOnSimulator();
}
